XaaSTrack/urls.py
from django.conf.urls import include, url
from django.contrib import admin, auth

from django.db.models.fields import CharField
from planman.views import register

urlpatterns = [
    # Examples:
    # url(r'^$', 'XaaSTrack.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^planman/', include('planman.urls')),
    url(r'^plaid/',include('trans.urls')),
    url(r'^',include('planman.urls')),

    ##Use stock auth views:
    ###https://docs.djangoproject.com/en/1.8/topics/auth/default/#module-django.contrib.auth.views
    url(r'^',include('django.contrib.auth.urls')),
    url(r'^register/',register,name="register")
]

# Build-in stock auth urls
# ^login/$ [name='login']
# ^logout/$ [name='logout']
# ^password_change/$ [name='password_change']
# ^password_change/done/$ [name='password_change_done']
# ^password_reset/$ [name='password_reset']
# ^password_reset/done/$ [name='password_reset_done']
# ^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$ [name='password_reset_confirm']
# ^reset/done/$ [name='password_reset_complete']

trans/urls.py
from django.conf.urls import url

from . import views
# check out https://docs.djangoproject.com/en/1.8/ref/urlresolvers/
# #module-django.core.urlresolvers for more info
from .views import *

urlpatterns = [

    #Creating Plaid Accounts
    url(r'^$', PlaidTokenList.as_view(), name='plaid-index'),
    url(r'^link$',views.plaidlink, name='plaid-link'),
    url(r'^link/submit$',views.plaidlink_submit, name='plaid-link-submit'),
    url(r'^token/list$',PlaidTokenList.as_view(),name='plaid-token-list'),
    url(r'^token/(?P<pk>\d+)/retrieve$',views.transactions_retrieve,name='plaid-token-retrieve'),
    #url(r'^token/(?P<pk>\d+)/transactions/$',PlaidTransactionList.as_view(),name='plaid-token-transactions'),

    #converting transactions
    url(r'^flag/$',PlaidTransactionList_Flag.as_view(),name='plaid-flag'),
    url(r'^flag/showall$',PlaidTransactionList.as_view(),name='plaid-transaction-list'),

    url(r'^flag/convert/(?P<pk>\w+)/$',views.transaction_convert,name='plaid-flag-convert'),
    #url(r'^flag/ignore/(?P<pk>\w+)/$',views.transaction_ignore,name='plaid-flag-ignore'),
    # url(r'^convert/$',views.transactions_convert,name='plaid-convert'),
    # url(r'^/flag/submit$',views.transactions_flag_submit,name='plaid-flag-submit'),
    # url(r'^/convert/submit$',views.transactions_convert_submit,name='plaid-convert-submit'),


]

    # url(r'^plan/$', UserPlanList.as_view(), name='userplan-list'),
    # url(r'^plan/new/$', UserPlanCreate.as_view(), name='userplan-create'),
    # url(r'^plan/(?P<pk>\d+)/$', UserPlanDetail.as_view(), name='userplan-detail'),
    # url(r'^plan/(?P<pk>\d+)/update$', UserPlanUpdate.as_view(), name='userplan-update'),
    # url(r'^plan/(?P<pk>\d+)/delete$', UserPlanDelete.as_view(), name='userplan-delete'),
    #
    # #Provider
    # url(r'^provider/$', PlanProviderList.as_view(), name='provider-list'),
    # url(r'^provider/new$', PlanProviderCreate.as_view(), name='provider-create'),
    # url(r'^provider/(?P<pk>\d+)/$', PlanProviderDetail.as_view(), name='provider-detail'),
    # url(r'^provider/(?P<pk>\d+)/update', PlanProviderUpdate.as_view(), name='provider-update'),
    # url(r'^provider/(?P<pk>\d+)/delete', PlanProviderDelete.as_view(), name='provider-delete'),
    #
    # ##events/payments
    # url(r'^plan/(?P<plan_id>\d+)/newevent/$', views.createEvent, name='event-create'),
    # url(r'^event/(?P<pk>\d+)/update', PlanEventUpdate.as_view(), name='event-update'),
    # url(r'^event/(?P<pk>\d+)/delete', PlanEventDelete.as_view(), name='event-delete'),

trans/models.py
# Create your models here.
from django.contrib.auth.models import User
from django.db import models
from django.core.urlresolvers import reverse
from django.utils import timezone

class PlaidUserToken(models.Model):  #really a plaid useraccount
    user=models.ForeignKey(User)
    access_token=models.CharField(verbose_name='token used to access account from plaid',max_length=200)
    last_sync=models.DateTimeField(blank=True,null=True)
    STATUS_TYPES = (('ok','Ok'),('connecting','In Process'),('failed','Needs Attention'),('new','New'))
    status = models.CharField(max_length=10,choices=STATUS_TYPES)
    status_text=models.CharField(max_length=128,blank=True)

class PlaidAccount(models.Model):
    usertoken = models.ForeignKey(PlaidUserToken)
    _id = models.CharField(max_length=50)
    _item = models.CharField(max_length=50)
    _user = models.CharField(max_length=50)
    name = models.CharField(verbose_name='Account Name',max_length=50,blank=True,null=True)
    type = models.CharField(verbose_name='Account Type', max_length=10)
    institution_type = models.CharField(max_length=10)
# [{'_id': 'aV4qOmw5YDTe8KR1vmJoUX1QEJq676fbnyxrm',
#   '_item': 'R0LwXJyoYbcAga61M3bYIXVbyj04AktovKanX',
#   '_user': 'OkdapOqoYBUmej765Q0YHQjzQ8Er7Mce6ZjbL',
#   'balance': {'available': 5192.12, 'current': 788.13},
#   'institution_type': 'chase',
#   'meta': {'limit': 6000, 'name': 'Amazon Credit Card', 'number': '3407'},
#   'type': 'credit'}]

class PlaidTransaction(models.Model):
    json_raw=models.TextField(blank=True)

    usertoken = models.ForeignKey(PlaidUserToken)
    account = models.ForeignKey(PlaidAccount)

    _account = models.CharField(max_length=50)
    _id = models.CharField(primary_key=True,max_length=50)
    amount=models.DecimalField(max_digits=10,decimal_places=2)
    date = models.DateField(blank=True,null=True)
    name=models.CharField(max_length=200)
    category=models.CharField(max_length=50,blank=True)
    type=models.CharField(max_length=50)
    meta=models.CharField(max_length=200,blank=True)
    meta_score=models.CharField(max_length=200,blank=True)
    STATE_NEW = 0
    STATE_FLAGGED = 1
    STATE_CONVERTED = 2
    STATE_CANCELLED = 3
    STATES = ((STATE_NEW,'new'),(STATE_FLAGGED,'flagged'),
              (STATE_CONVERTED,'converted'),(STATE_CANCELLED,'ignored'))
    state = models.SmallIntegerField(choices=STATES)

# {'_account': 'aV4qOmw5YDTe8KR1vmJoUX1QEJq676fbnyxrm',
#   '_id': 'Bn7ZXV9pa3Sabn51v0m3CQ88ezm4AMcNmaRqX',
#   'amount': -2780.52,
#   'category': ['Payment', 'Credit Card'],
#   'category_id': '16001000',
#   'date': '2015-03-05',
#   'meta': {'location': {}},
#   'name': 'Credit Card Payment',
#   'pending': False,
#   'score': {'location': {}, 'name': 1},
#   'type': {'primary': 'special'}},
#  {'_account': 'aV4qOmw5YDTe8KR1vmJoUX1QEJq676fbnyxrm',
#   '_id': 'AQg7XNaV4KceboMKngLJUwxxZ8dqyDTjmJgYr',
#   'amount': 1.5,
#   'date': '2015-03-04',
#   'meta': {'location': {'city': 'Chicago', 'state': 'IL', 'zip': '60651'}},
#   'name': 'COCA COLA CHICAGO IL',
#   'pending': False,
#   'score': {'location': {'city': 1, 'state': 1, 'zip': 1}, 'name': 0.2},
#   'type': {'primary': 'place'}}]



# class UserProfile(models.Model):
#     user = models.OneToOneField(User)
#     lastsync = models.DateTimeField('Last time user loaded transactions',blank=True,null=True)
#     def __str__(self):
#         return self.user.username
#
# class PlanProvider(models.Model):
#     name = models.CharField(max_length=200)
#     def __str__(self):
#         return self.name
#     def get_absolute_url(self):
#         return reverse('provider-detail', kwargs={'pk':self.pk})
#
# class UserPlan(models.Model):
#
#     #description
#     user_description = models.CharField(max_length=200,verbose_name="Description",blank=True,help_text="form help text")
#     user = models.ForeignKey(User,verbose_name='*useraccount')
#     planprovider_text = models.CharField(max_length=200,verbose_name='Service Provider')
#     planprovider_key = models.ForeignKey(PlanProvider,verbose_name='*service provider _ key',blank=True,null=True,on_delete=models.SET_NULL)
#     notes=models.TextField(blank=True,verbose_name="Notes")
#
#     #plan start/end/renewal
#     start_date = models.DateField(null=True,blank=True)
#     next_renewal_date = models.DateField(null=True,blank=True)
#     expiration_date = models.DateField(null=True,blank=True)
#
#
#     #payment schedule
#     last_payment_date = models.DateField(null=True,blank=True)
#     next_payment_date = models.DateField(null=True,blank=True)
#     has_recurring_payment = models.BooleanField(default=False,verbose_name ="Has Recurring Payments?")
#     recurring_payment_amount = models.DecimalField(null=True,blank=True,max_digits=10,decimal_places=2,verbose_name="Recurring Payment Amount")
#     recurring_payment_months = models.PositiveSmallIntegerField(default=1,null=True,blank=True,verbose_name="Recurring Payment Occurs every X Months")
#
#     def get_amount_last_month(self):
#         amount = sum( (0 if not e.amount else e.amount) for e in self.planevent_set.filter(event_type='pay'))
#         if amount>0: return amount
#         if(self.recurring_payment_amount):
#             return self.recurring_payment_amount
#         return Decimal(0.0)
#
#
#     def get_year_to_date(self):
#         amount = sum((0 if not e.amount else e.amount) for e in self.planevent_set.filter(event_type='pay'))
#         if amount>0: return amount
#         return Decimal(0.0)
#
#     def __str__(self):
#         if len(self.user_description)>0:
#             return self.planprovider_text + " (" + self.user_description + ")"
#         else:
#             return self.planprovider_text
#
#     def get_absolute_url(self):
#         return reverse('userplan-detail', kwargs={'pk':self.pk})
#
# class PlanEvent(models.Model):
#     PLANEVENT_TYPES = (('pay','pay'),('start','start'),('stop','stop'),('renew','renew'))
#     userplan = models.ForeignKey(UserPlan)
#     event_type = models.CharField(max_length=8,choices=PLANEVENT_TYPES)
#     event_date = models.DateField()
#
#     amount = models.DecimalField(max_digits=10,decimal_places=2,blank=True,null=True)
#     user_description = models.CharField(max_length=200,blank=True)
#
#     def __str__(self):
#         return self.userplan.__str__() + ":" + self.event_type +":" + self.user_description

trans/views.py
from django.http.response import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.views.generic.edit import UpdateView
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from planman.models import UserPlan,PlanEvent


# Create your views here.
from trans.plaidapi import PlaidAPI
from trans.models import PlaidUserToken, PlaidTransaction
from django.http.response import HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy

from planman.forms import PlanEvent_ConversionForm


class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view)

# https://github.com/plaid/link
@login_required
def plaidlink(request):
    public_key='test_key'
    client_id = 'test_id'
    context = {'client_id': PlaidAPI.client_id,
               'product': 'connect',
               'public_key': PlaidAPI.public_key,
               'env': PlaidAPI.env
               }
    return render(request, 'trans/plaidlink.html', context)

@login_required
def plaidlink_submit(request):
    print('request')
    print(request.GET)
    if request.GET: public_token = request.GET.get('public_token',None)
    if not public_token:
        return HttpResponse("Expected a GET request with token")
    print('Token:')
    print(public_token)


    ##Exchange token and create account
    plaidaccount = PlaidAPI().exchangeLinkTokenForAccount(request.user,public_token)
    context={'plaidaccount':plaidaccount}
    return render(request, 'trans/plaidlinksubmit.html', context)

@login_required
def transactions_retrieve(request, pk):
    plaidaccount = get_object_or_404(PlaidUserToken,pk=pk)
    print('Retrieving transactions')
    new_transaction_list = PlaidAPI().getTransactions(plaidaccount)
    messages.success(request,"Successfully retrieved {0} new transactions".format(len(new_transaction_list)))
    return HttpResponseRedirect(reverse_lazy('plaid-index'))

    #return render(request, 'trans/plaidlink.html', context)

class PlaidTransactionList(LoginRequiredMixin, ListView):
    model = PlaidTransaction
    template_name='trans/transactions_flag.html'
    def get_context_data(self, **kwargs):  ##adding additional context data
        context = super(PlaidTransactionList, self).get_context_data(**kwargs)
        context['showing_all']=True
        return context
    def get_queryset(self):
        return PlaidTransaction.objects.order_by('date')

class PlaidTransactionList_Flag(LoginRequiredMixin, ListView):
    model = PlaidTransaction
    template_name='trans/transactions_flag.html'
    def get_queryset(self):
        return PlaidTransaction.objects.filter(state=PlaidTransaction.STATE_NEW,
                                               usertoken__user=self.request.user).order_by('date')
    def get_context_data(self, **kwargs):  ##adding additional context data
        context = super(PlaidTransactionList_Flag, self).get_context_data(**kwargs)
        form=PlanEvent_ConversionForm()
        form.fields['userplan'].queryset=UserPlan.objects.filter(user=self.request.user)
        context['form_convert_existing']=form
        return context


@login_required()
def transaction_convert(request,pk):
    transaction=get_object_or_404(PlaidTransaction,pk=pk)

    context = {'transaction':transaction}

    #process data if its a post method
    if request.method == 'POST':
        event_form = PlanEvent_ConversionForm(data=request.POST)
        userplan=None
        if 'ignore' in request.POST:
            ##process ignore
                transaction.state=PlaidTransaction.STATE_CANCELLED
                transaction.save()
                messages.warning(request,"Transaction '{0}/{1}' discarded".format(transaction.date,transaction.name) )
                return HttpResponseRedirect(reverse_lazy('plaid-flag'))
        if 'newplan' in request.POST:
            ##process the creation of a new plan
            userplan = UserPlan(user=request.user,
                                    planprovider_text=transaction.name,
                                    notes="Provider automatically created from {3} transaction labeled '{0}' on {1} for {2}".format(transaction.name,transaction.date,transaction.amount,transaction.account.name),
                                    recurring_payment_amount = transaction.amount)
            userplan.save()
            messages.success(request,"Created new plan: {0}".format(userplan))
        elif 'convert' in request.POST:
            ##process the conversion into an existing plan
            event_form=PlanEvent_ConversionForm(data=request.POST)
            if event_form.is_valid():
                userplan = get_object_or_404(UserPlan,pk=event_form.cleaned_data['userplan'].pk)
                #userplan=event_form.userplan
            else:
                for error in event_form.non_field_errors():
                    messages.error(request,error)
                for error in event_form.errors:
                    if error=='__all__': continue
                    messages.error(request,"{0}: {1}".format(error,event_form.errors[error]))
        else:
            messages.error(request,"Unknown form submission?")

        if userplan:
            ##add the transaction as a payment
            payment = PlanEvent(userplan=userplan,
                                event_type='pay',
                                event_date=transaction.date,
                                amount=transaction.amount,
                                user_description="{0} ({1})".format(transaction.name,transaction.account.name))
            payment.save()
            transaction.state=PlaidTransaction.STATE_CONVERTED
            transaction.save()
            messages.success(request,'Added payment: {0} [{1}]<br><a href="{2}">Process more transactions...</a>'.format(payment.user_description,payment.event_date,reverse_lazy('plaid-flag')))
            return HttpResponseRedirect(reverse_lazy('userplan-detail',kwargs={'pk':userplan.pk}) + "?highlight={0}".format(payment.id))
    #if not a post, or not a valid plan, go back
    return HttpResponseRedirect(reverse_lazy('plaid-flag'))

@login_required()
def transaction_ignore(request,pk):
    transaction=get_object_or_404(PlaidTransaction,pk=pk)
    transaction.state=PlaidTransaction.STATE_CANCELLED
    transaction.save()
    messages.warning(request,"Transaction '{0}/{1}' discarded".format(transaction.date,transaction.name) )
    return HttpResponseRedirect(reverse_lazy('plaid-flag'))


@login_required
def transactions_convert_submit(request):
    return HttpResponse("Flagging was submitted")

@login_required
def transactions_flag_submit(request):
    return HttpResponse("Flagging was submitted")


###generic views
class PlaidTokenList(LoginRequiredMixin, ListView):
    model = PlaidUserToken
    def get_queryset(self):
        return PlaidUserToken.objects.filter(user=self.request.user)


class PlaidTokenUpdate(LoginRequiredMixin, UpdateView):
    model = PlaidUserToken
    template = 'trans/plaidaccount_update.html'

trans/templates/trans/plaidlink.html
{% extends 'base.html' %}
{% load bootstrap3 %}


{#Using Plaid Link#}
{#https://github.com/plaid/link#step-1-get-your-public_key#}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h1 class="panel-title">
                Connect to Plaid
            </h1>
        </div>
        <div class="panel-body">
            <div>
            <!-- A hidden input named public_token will be appended to this form
once the user has completed the Link flow. Link will then submit the
form, sending the public_token to your server. -->
            <form id="plaid-link-form-id" method="GET" action="{% url 'plaid-link-submit' %}"></form>

            <script
                    src="https://cdn.plaid.com/link/stable/link-initialize.js"
                    data-client-name="{{ client_id }}"
                    data-form-id="plaid-link-form-id"
                    data-key="{{ public_key }}"
                    data-product="{{ product }}"
                    data-env="{{ env }}">
            </script>
</div>
            <hr>

            <small><p>SubTrack uses <a href="https://plaid.com/">Plaid</a> to securely access your bank or credit card transaction data.  </p>
            <p>We <i>never</i> touch your bank credentials ourselves.  When you click the button below, a <a href="https://github.com/plaid/link">Plaid Link</a>
                session will appear on your screen.  Once you complete the authorization process, SubTrack will be able to download transactions from Plaid's servers.
                </p></small>
        </div>
        <div class="panel-footer">
            <a href="/">< Home</a>
        </div>
    </div>
{% endblock %}


{##}
{#            <h3>Userplan</h3>#}
{#            <form action="" method="post">#}
{#                {% csrf_token %}#}
{#                {% bootstrap_form form %}#}
{#                {% buttons submit='Save' %}#}
{#                    {% if userplan %}#}
{#                        <span style="float:right">#}
{#                        <a href="{{ userplan.get_absolute_url }}delete" class="btn btn-danger"><i class="fa fa-trash"></i></a>#}
{#                        </span>#}
{#                    {% endif %}#}
{#                {% endbuttons %}#}
{#            </form>#}

trans/templates/trans/plaidlinksubmit.html
{% extends 'base.html' %}
{% load bootstrap3 %}


{#Using Plaid Link#}
{#https://github.com/plaid/link#step-1-get-your-public_key#}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h1 class="panel-title">
                Account Connected!
            </h1>
        </div>
        <div class="panel-body">
            <h3>We've successfully linked to your account!</h3>
            <p>Status Text: {{ plaidaccount.status_text }}
            </p>
            <p>We'll retrieve the transactions for you shortly</p>
            <p></p>
            <p>When you are ready, you can <a href="{% url 'plaid-token-list' %}">
                view all your linked accounts</a></p>
        </div>
        <div class="panel-footer">
            <a href="/">< Home</a>
        </div>
    </div>
{% endblock %}


{##}
{#            <h3>Userplan</h3>#}
{#            <form action="" method="post">#}
{#                {% csrf_token %}#}
{#                {% bootstrap_form form %}#}
{#                {% buttons submit='Save' %}#}
{#                    {% if userplan %}#}
{#                        <span style="float:right">#}
{#                        <a href="{{ userplan.get_absolute_url }}delete" class="btn btn-danger"><i class="fa fa-trash"></i></a>#}
{#                        </span>#}
{#                    {% endif %}#}
{#                {% endbuttons %}#}
{#            </form>#}

trans/templates/trans/plaidtransaction_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}


{#Using Plaid Link#}
{#https://github.com/plaid/link#step-1-get-your-public_key#}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h1 class="panel-title">
                Transaction List
            </h1>
        </div>
        <div class="panel-body">
 <ul>
        {% for object in object_list %}
        <li>{{ object.id }}{{ object.name }}</li>
        {% endfor %}
    </ul>

        </div>
        <div class="panel-footer">
            <a href="/">< Home</a>
        </div>
    </div>
{% endblock %}


{##}
{#            <h3>Userplan</h3>#}
{#            <form action="" method="post">#}
{#                {% csrf_token %}#}
{#                {% bootstrap_form form %}#}
{#                {% buttons submit='Save' %}#}
{#                    {% if userplan %}#}
{#                        <span style="float:right">#}
{#                        <a href="{{ userplan.get_absolute_url }}delete" class="btn btn-danger"><i class="fa fa-trash"></i></a>#}
{#                        </span>#}
{#                    {% endif %}#}
{#                {% endbuttons %}#}
{#            </form>#}

trans/templates/trans/plaidusertoken_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}


{#Using Plaid Link#}
{#https://github.com/plaid/link#step-1-get-your-public_key#}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h1 class="panel-title">
                Your Connections with Plaid
                <span style="float:right">
                {# button was here #}
                </span>
            </h1>
        </div>
        <div class="panel-body">
        <div>
        <a href="{% url 'plaid-link' %}" class="btn btn-success btn-sm">
                <i class="fa fa-plus"></i> Link new account
                </a>
            <a href="{% url 'plaid-flag' %}" class="btn btn-default btn-sm">
                <i class="fa fa-bolt"></i> Process Transactions
                </a>
        </div>
        <p></p>
        <hr>
        <b>Your connections:</b>

 <ul class="list-group">
        {% for usertoken in object_list %}
        <li class="list-group-item"><b>Connection Id #: {{ usertoken.name }} {{ usertoken.access_token|truncatechars:8  }}</b>.
            <br>Status: {{ usertoken.status_text }}
                        <p>Accounts:
            <ul>
            {% for account in usertoken.plaidaccount_set.all %}

            <li>
                {{ account.name }} ( {{account.type }} : {{ account.institution_type }})
            </li>
                {% endfor %}
            </p>
            </ul>
        <br><a href="{% url 'plaid-token-retrieve' usertoken.id %}" class="btn btn-warning btn-sm"><i class="fa fa-refresh"></i> Refresh Connection</a>


        </li>
        {% endfor %}
    </ul>

        </div>
        <div class="panel-footer">
            <a href="/">< Home</a>
        </div>
    </div>
{% endblock %}


{##}
{#            <h3>Userplan</h3>#}
{#            <form action="" method="post">#}
{#                {% csrf_token %}#}
{#                {% bootstrap_form form %}#}
{#                {% buttons submit='Save' %}#}
{#                    {% if userplan %}#}
{#                        <span style="float:right">#}
{#                        <a href="{{ userplan.get_absolute_url }}delete" class="btn btn-danger"><i class="fa fa-trash"></i></a>#}
{#                        </span>#}
{#                    {% endif %}#}
{#                {% endbuttons %}#}
{#            </form>#}

trans/templates/trans/transactions_flag.html
{% extends 'base.html' %}
{% load bootstrap3 %}


{#Using Plaid Link#}
{#https://github.com/plaid/link#step-1-get-your-public_key#}

{% block content %}
        <div class="panel panel-default">
        <div class="panel-heading">
            <h1 class="panel-title">
                Transaction List
            </h1>
        </div>
        <div class="panel-body">
        <table class="table">
            <tr>
                <th>Date</th>
                <th>Name</th>
                <th>Amount</th>
                {% if showing_all %}
                <th>State</th>
                {% endif %}
                <th><span style="text-align: center; width:100%">Action</span></th>
            </tr>
            {% for transaction in object_list %}
            <tr>
                <td>{{ transaction.date }}</td>
                <td>{{ transaction.name }}</td>
                <td>{{ transaction.amount }}</td>
                {% if showing_all %}
                <td>{{ transaction.get_state_display }}</td>
                {% endif %}

                <td>
                    {% bootstrap_form_errors form_convert_existing %}
                    <form action="{% url 'plaid-flag-convert' transaction.pk %}" method="post" style="margin:0; padding:0;display:inline">
                    {% csrf_token %}
                        {{ form_convert_existing.userplan }}

                        <button type="submit" name="convert" class="btn btn-success btn-sm" title="Tag this transaction onto an existing plan"/>
                            <i class="fa fa-tag"></i>
                        </button>
                    </form>
                     |
                <form action="{% url 'plaid-flag-convert' transaction.pk %}" method="post" style="margin:0; padding:0;display:inline">
                    {% csrf_token %}
                        <button type="submit" name="newplan" class="btn btn-warning btn-sm" title="Convert this transaction into a new plan"/>
                            <i class="fa fa-plus-circle"></i>
                        </button>
                </form>
                <form action="{% url 'plaid-flag-convert' transaction.pk %}" method="post" style="margin:0; padding:0;display:inline">
                    {% csrf_token %}
                        <button type="submit" name="ignore" class="btn btn-danger btn-sm" title="Ignore/Discard Transaction"/>
                            <i class="fa fa-bell-slash-o"></i>
                        </button>
                </form>
                </td>
            </tr>
            {% endfor %}
        </table>

        </div>
        <div class="panel-footer">
            <a href="/">< Home</a>
        </div>
    </div>
{% endblock %}

{% block gridstart %}
    <div class="col-sm-1"></div>
    <div class="col-md-10">
{% endblock %}

{##}
{#            <h3>Userplan</h3>#}
{#            <form action="" method="post">#}
{#                {% csrf_token %}#}
{#                {% bootstrap_form form %}#}
{#                {% buttons submit='Save' %}#}
{#                    {% if userplan %}#}
{#                        <span style="float:right">#}
{#                        <a href="{{ userplan.get_absolute_url }}delete" class="btn btn-danger"><i class="fa fa-trash"></i></a>#}
{#                        </span>#}
{#                    {% endif %}#}
{#                {% endbuttons %}#}
{#            </form>#}